# Generated by Django 3.2 on 2023-02-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
